name: Blob storage website CI

on:
push:
    branches: [ master ]

jobs:
build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Azure Login
    uses: azure/login@v1
    with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}    
    - name: Push to storage blob
    uses: azure/CLI@v1
    with:
        azcliversion: 2.0.72
        inlineScript: |
            az storage blob upload-batch --account-name wildmeorg -d '$web' -s .
    - name: Azure CLI script
    uses: azure/CLI@v1
    with:
        azcliversion: 2.0.72
        inlineScript: |
        az cdn endpoint purge --content-paths  "/*" --profile-name "react-cdn" --name "wildmedotorg" --resource-group "react"
        # Azure logout 
    - name: logout
      run: |
            az logout
